import React from "react";
import Link from "next/link";
const Home = () => {
  return (
    <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
      <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
      <p style={{ fontSize: "18px", marginBottom: "30px" }}>
        This project was generated By{" "}
        <a href="https://www.dhiwise.com" style={{ color: "#87CEFA", textDecoration: "none" }}>
          Dhiwise
        </a>
        . Quickly use below links to navigate through all pages.
      </p>
      <ul style={{ listStyle: "none", padding: "0" }}>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/DetailReview" style={{ color: "#87CEFA", textDecoration: "none" }}>
            DetailReview
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/wishlist" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Wishlist
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/team" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Team
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/blog" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Blog
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/blogdetail" style={{ color: "#87CEFA", textDecoration: "none" }}>
            BlogDetail
          </Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
